;5# **Assignment For Numpy**


Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
a = np.zeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [ ]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [ ]:
print(b.shape)

(40,)


5. Print the type of the previous array in question 3

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config)


1.19.4
<function show at 0x7f01e9bd0620>


7. Print the dimension of the array in question 3


In [ ]:
print(b.shape)

(40,)


8. Create a boolean array with all the True values

In [ ]:
a = np.array([1,1,1,1], dtype = bool)
print(a)

[ True  True False  True]


9. Create a two dimensional array




In [ ]:
b = np.arange(20).reshape(4,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


10. Create a three dimensional array



In [ ]:
b = np.arange(36).reshape(3,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
a = np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
a = np.zeros(10)
a[4]= 1
print(a)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [ ]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype= float)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr1)
print(arr2)
x = arr1*arr2
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],  [7., 2., 12.]])
compar = arr1 == arr2
print(compar)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [ ]:
a = np.arange(0,10)
print(a)
print(a[1:10:2])


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [ ]:
print(a)
a[1:10:2] =-1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
print(arr)
arr[5:9] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
n = 5

import numpy as np

border_array = np.ones((n, n), dtype = int)
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 
 
            [7, 8, 9]])
print(arr2d)
arr2d[1:2,1:2]=12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [2]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0,0:3,0:3] = 64
print("Convert all the values of 1st array to 64")
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Convert all the values of 1st array to 64
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [17]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr2d)
print("slice out the first 1st 1-D array from it \n")
print(arr2d[0])

[[0 1 2 3 4]
 [5 6 7 8 9]]
slice out the first 1st 1-D array from it 

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [16]:
print(arr2d[1,1])

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [20]:
print(arr2d[:,2])

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [48]:
b = np.random.random((10,10))
print(b)
print("Minimun value is = " ,np.min(b))
print("Max value is = ",np.max(b))

[[0.12533171 0.55787223 0.88964787 0.37959793 0.77178213 0.0737921
  0.18928669 0.83023557 0.73069298 0.2227235 ]
 [0.68010116 0.0383701  0.45652482 0.17064604 0.4135292  0.31742661
  0.59369256 0.76050451 0.80908392 0.9359202 ]
 [0.49174927 0.09288181 0.18045046 0.19007742 0.29627243 0.53856426
  0.89620228 0.50398608 0.50902738 0.98172985]
 [0.66018412 0.5487891  0.72595633 0.45676597 0.41726598 0.3530912
  0.07347115 0.59999138 0.91314055 0.17931824]
 [0.00394388 0.72739976 0.65204235 0.87694891 0.50608238 0.2240165
  0.17469636 0.18786241 0.41319496 0.44423492]
 [0.24015315 0.38987321 0.67127779 0.1623286  0.40249608 0.15640453
  0.8958441  0.42178432 0.26057429 0.09342663]
 [0.63079614 0.66566104 0.29764707 0.44952778 0.48563325 0.49200019
  0.46022498 0.90739781 0.35653921 0.05425511]
 [0.36890527 0.73104865 0.51116207 0.37320559 0.16356391 0.87391039
  0.82990104 0.72124523 0.27523788 0.03749247]
 [0.1862877  0.64626229 0.2772503  0.25872754 0.35275037 0.61526839
  0.147344   0.

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([np.where(a==b)])

[(array([1, 3, 5, 7]),)]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [112]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

data = np.random.randn(7, 4)
print('\n',data[names!="Will"])




 [[ 2.0751236  -1.83531231 -0.54932016 -0.50157646]
 [-0.1285032  -0.16541369  2.39941249 -0.56325947]
 [-0.78051178 -0.57686543  0.83608504 -1.62995623]
 [-1.10206615 -0.22269238 -0.560196   -0.35723649]
 [-0.10978291 -0.41647076 -0.84719305  0.02069771]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [113]:
data[~(names == 'Joe') | ~(names == 'Will')]

array([[ 2.0751236 , -1.83531231, -0.54932016, -0.50157646],
       [-0.1285032 , -0.16541369,  2.39941249, -0.56325947],
       [-0.29874691, -0.29146136, -0.99154922,  1.12410773],
       [-0.78051178, -0.57686543,  0.83608504, -1.62995623],
       [-1.16777902, -0.21795312, -0.20607664, -1.04518123],
       [-1.10206615, -0.22269238, -0.560196  , -0.35723649],
       [-0.10978291, -0.41647076, -0.84719305,  0.02069771]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
a = np.arange(1,16).reshape(5,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [49]:
a = np.arange(1,17).reshape(2, 2, 4)
print(a)
print("Swap axis is ", np.transpose(a))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Swap axis is  [[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


33. Swap axes of the array you created in Question 32

In [ ]:

print(a[::-1])

[[[ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [108]:

a = np.arange(10)
print(a)

b = np.square(a)
print("\n square root of array is ", b)
print(np.where(b < 0.5,0,b))

[0 1 2 3 4 5 6 7 8 9]

 square root of array is  [ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [109]:
ar1=np.array(np.random.rand(12))
ar2=np.array(np.random.rand(12))
print('\n',ar1)
print('\n',ar2)
print('\n',np.where(ar1>ar2,ar1,ar2))
print('\n',np.where(ar2>ar1,ar2,ar1))


 [0.94588924 0.64408924 0.06276409 0.80488379 0.3338275  0.22385675
 0.07665825 0.63397627 0.61913261 0.02447638 0.08736664 0.35148477]

 [0.23496963 0.13602084 0.42179325 0.42126206 0.85242286 0.62476747
 0.28286704 0.89231377 0.70616921 0.24708201 0.82088237 0.7491928 ]

 [0.94588924 0.64408924 0.42179325 0.80488379 0.85242286 0.62476747
 0.28286704 0.89231377 0.70616921 0.24708201 0.82088237 0.7491928 ]

 [0.94588924 0.64408924 0.42179325 0.80488379 0.85242286 0.62476747
 0.28286704 0.89231377 0.70616921 0.24708201 0.82088237 0.7491928 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
print("Unique name is ", a)
print(np.sort(a))

Unique name is  ['Bob' 'Joe' 'Will']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [86]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))


[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [93]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
x = np.delete(sampleArray, obj = 1, axis=1)
print("deleteing column \n", x)
newColumn = np.array([[10,10,10]])
y = np.insert(x, 1, newColumn,1)
print("New column \n", y)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
deleteing column 
 [[34 73]
 [82 12]
 [53 66]]
New column 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [94]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [95]:
r=np.random.randn(20)
print(r)
print('\n',r.cumsum())

[-1.53658026  0.86434985  0.47800875  0.62879206  0.2035068  -0.35630585
  0.30352082  0.55469729  0.60956303  0.06068235  1.36665621  0.66268706
 -1.06652125 -0.8754578  -0.54293468  0.33940435 -1.75725997 -0.40032206
  0.83731885 -1.46311496]

 [-1.53658026 -0.67223041 -0.19422167  0.4345704   0.6380772   0.28177135
  0.58529217  1.13998945  1.74955248  1.81023483  3.17689104  3.8395781
  2.77305684  1.89759904  1.35466436  1.69406871 -0.06319125 -0.46351331
  0.37380554 -1.08930941]
