# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
print("2D array \n", arr.reshape(2,5))

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
a = np.arange(0,10).reshape(2,5)
print("Array 1 \n ", a)
b = np.ones([2,5], int)
print("Array 2 \n ", b)
print("Verticle stack \n", np.vstack((a,b)))




Array 1 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
Array 2 
  [[1 1 1 1 1]
 [1 1 1 1 1]]
Verticle stack 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
a = np.arange(0,10).reshape(2,5)
print("Array 1 \n ", a)
b = np.ones([2,5], int)
print("Array 2 \n ", b)
print("Horizontal stack \n", np.hstack((a,b)))

Array 1 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
Array 2 
  [[1 1 1 1 1]
 [1 1 1 1 1]]
Verticle stack 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a = np.arange(0,10).reshape(2,5)
print(a)
print("flat 1d array n", a.flatten() )

[[0 1 2 3 4]
 [5 6 7 8 9]]
flat 1d array n [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [39]:
a = np.arange(0,15).reshape(3,5)
print(a)
print(a.ravel())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [42]:
a = np.arange(0,15).reshape(1,15)
print(a)
print("Higher dimention \n", np.hsplit(a,5))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
Higher dimention 
 [array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]]), array([[12, 13, 14]])]


## Question:7

### Create 5x5 an array and find the square of an array?

In [20]:
a = np.arange(25).reshape(5,5)
print(a)
print("Square of array \n", np.square(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Square of array 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [22]:
a = np.arange(30).reshape(5,6)
print(a)
print("mean of array \n", a.mean())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Square of array 
 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [23]:
print("S.deviation of array \n", a.std())

S.deviation of array 
 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [25]:
print("median of array \n", np.median(a))

Square of array 
 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [27]:
print("transpose of array \n", np.transpose(a))

transpose of array 
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [30]:
a = np.arange(16).reshape(4,4)
print(a)
print("sum of diagonal elements \n", np.trace(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of diagonal elements 
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [32]:
print("sum of diagonal elements \n", np.linalg.det(a))

sum of diagonal elements 
 0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [33]:
print('\n',np.percentile(a,5))
print(np.percentile(a,95))


 0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [34]:

print(a)
print('\n',np.isnan(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
