# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

1. Start by importing NumPy as np

In [1]:
#type your code here
import numpy as np



In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [3]:
#type your code here
cupcakes=np.array([2,0.75,2,1,0.5])
print("cupcakes")

cupcakes


3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [5]:
#type your code here
import numpy as np
my_data = np.genfromtxt('/content/gdrive/MyDrive/PIAIC/recipes.csv', delimiter=',')
print(my_data)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [10]:
#type your code here
print('\t Flour','\t Sugar','\t Eggs','\t Butter')
print('Cupcakes', my_data[0])
print('Pancake' , my_data[1])
print('Cookie'  , my_data[2])
print('Bread'   , my_data[3])

	 Flour 	 Sugar 	 Eggs 	 Butter
Cupcakes [2.   0.75 2.   1.   0.5 ]
Pancake [1.    0.125 1.    1.    0.125]
Cookie [2.75 1.5  1.   0.   1.  ]
Bread [4.  0.5 2.  2.  0.5]


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [42]:
#type your code here
eggs = my_data[:,2]
print(eggs)

[2. 1. 1. 2.]


6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [43]:
#type your code here
print(my_data[eggs == 1])


[[1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]]


7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [45]:
#type your code here
cookies = my_data[2,:]
print(cookies)

[2.75 1.5  1.   0.   1.  ]


8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [46]:
#type your code here
double_batch = cupcakes*2
double_batch 

array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [47]:
#type your code here
grocery_list = cookies+double_batch
grocery_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])